language: node_js

before_install:
  - sudo apt-get update -qq
  # - sudo apt-get install -y nasm

node_js:
  - "8.12.0"

before_script:
  - npm install coveralls

script:
  - npm run lint
  - npm run coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js